server:
  port: 8080
  servlet:
    context-path: /shiroboot
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiroboot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wdc
    password: w0fng_client
  http:
    log-request-details: true
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: test
    username: nacos
    password: nacos