server:
  port: 8080
  servlet:
    context-path: /shiroboot
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiroboot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wdc
    password: w0fng_client
  http:
    log-request-details: true
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848
    namespace: 67cf667d-7bd2-4de1-9cf9-39ba6fb51a0b
    type: yaml
    data-id: shiroboot
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
    auto-refresh: true
